server:
  port: 12120
  servlet:
    context-path: /spring-data-elasticsearch

# application.yml \u6587\u4EF6
spring:
  profiles:
    include:
#      - db
      - bocidb
      - es
      - redis

total:
  count: 10000
page:
  size: 10

thread:
  num:
    getOneDocument: 10
    esInsert: 10